//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este conversor puede convertir números a letras en cardinal, números en letras ordinal, números en letras fraccionario o partitivo,.
        /// </summary>
        internal static string Bienvenida1_1 {
            get {
                return ResourceManager.GetString("Bienvenida1.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a multiplicativo, decimal, romano, colectivo, número de sílabas, nombre de polígonos y poliedros, edades y nacido.
        /// </summary>
        internal static string Bienvenida1_2 {
            get {
                return ResourceManager.GetString("Bienvenida1.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a      El conversor ofrece información morfológica, ortográfica y gramatical de cada uno de los números convertidos a letras. .
        /// </summary>
        internal static string Bienvenida1_3 {
            get {
                return ResourceManager.GetString("Bienvenida1.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Además, se incluyen ejemplos que ayudan a la comprensión y buen uso..
        /// </summary>
        internal static string Bienvenida1_4 {
            get {
                return ResourceManager.GetString("Bienvenida1.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba un número sin coma ni punto para los miles o millones. Los miles o millones se pueden separar con un espacio en blanco..
        /// </summary>
        internal static string Bienvenida2_1 {
            get {
                return ResourceManager.GetString("Bienvenida2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En los decimales puede usar un punto o una coma. Para escribir fracciones use la barra inclinada &quot;/&quot;. .
        /// </summary>
        internal static string Bienvenida2_2 {
            get {
                return ResourceManager.GetString("Bienvenida2.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Para escribir en notación científica use la E sin espacios. Si es un número romano, escriba en mayúscula todos sus símbolos..
        /// </summary>
        internal static string Bienvenida2_3 {
            get {
                return ResourceManager.GetString("Bienvenida2.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con el símbolo.
        /// </summary>
        internal static string ConSimbolo {
            get {
                return ResourceManager.GetString("ConSimbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dólares.
        /// </summary>
        internal static string Dolar {
            get {
                return ResourceManager.GetString("Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los símbolos de monedas (£, ¥, etc.) no están admitidos para este idioma..
        /// </summary>
        internal static string ErrorLinea1 {
            get {
                return ResourceManager.GetString("ErrorLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede que el número, el exponente o la parte decimal sea demasiado grande..
        /// </summary>
        internal static string ErrorLinea2 {
            get {
                return ResourceManager.GetString("ErrorLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO escriba el número con letras, excepto si es un número romano..
        /// </summary>
        internal static string ErrorLinea3 {
            get {
                return ResourceManager.GetString("ErrorLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba un número sin coma ni punto para los miles o millones:.
        /// </summary>
        internal static string ErrorLinea4 {
            get {
                return ResourceManager.GetString("ErrorLinea4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los miles o millones se pueden separar con un espacio en blanco: .
        /// </summary>
        internal static string ErrorLinea5 {
            get {
                return ResourceManager.GetString("ErrorLinea5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En los decimales puede usar un punto o una coma:.
        /// </summary>
        internal static string ErrorLinea6 {
            get {
                return ResourceManager.GetString("ErrorLinea6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para escribir fracciones use la barra:.
        /// </summary>
        internal static string ErrorLinea7 {
            get {
                return ResourceManager.GetString("ErrorLinea7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para escribir en notación científica use la.
        /// </summary>
        internal static string ErrorLinea8_1 {
            get {
                return ResourceManager.GetString("ErrorLinea8.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sin espacios:.
        /// </summary>
        internal static string ErrorLinea8_2 {
            get {
                return ResourceManager.GetString("ErrorLinea8.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si es un número romano, escríbalo en mayúscula:.
        /// </summary>
        internal static string ErrorLinea9 {
            get {
                return ResourceManager.GetString("ErrorLinea9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba cantidades en.
        /// </summary>
        internal static string EscribaCantidades {
            get {
                return ResourceManager.GetString("EscribaCantidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los formatos admitidos para el catalán son los siguientes:.
        /// </summary>
        internal static string FormatosAdmitidos {
            get {
                return ResourceManager.GetString("FormatosAdmitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nosotros.
        /// </summary>
        internal static string Nosotros {
            get {
                return ResourceManager.GetString("Nosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba un número con cifras o un número romano.
        /// </summary>
        internal static string PlaceHolderNumero {
            get {
                return ResourceManager.GetString("PlaceHolderNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba los ejemplos.
        /// </summary>
        internal static string PruebaEjemplos {
            get {
                return ResourceManager.GetString("PruebaEjemplos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Números a letras.
        /// </summary>
        internal static string TituloPrincipal {
            get {
                return ResourceManager.GetString("TituloPrincipal", resourceCulture);
            }
        }
    }
}
