//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal.
        /// </summary>
        internal static string DecimalTipo {
            get {
                return ResourceManager.GetString("DecimalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplos.
        /// </summary>
        internal static string EjemplosTitulo {
            get {
                return ResourceManager.GetString("EjemplosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiero ... de chocolate. (Sustantivo).
        /// </summary>
        internal static string FraccionarioEjemplo1 {
            get {
                return ResourceManager.GetString("FraccionarioEjemplo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sequía afecta a ... de la región. (Adjetivo).
        /// </summary>
        internal static string FraccionarioEjemplo2 {
            get {
                return ResourceManager.GetString("FraccionarioEjemplo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las formas de los numerales fraccionarios coinciden con las del numerales ordinales con algunas excepciones: medio(2), cuarto(4), tercio(3) o décimo(10).
        /// </summary>
        internal static string FraccionNota1 {
            get {
                return ResourceManager.GetString("FraccionNota1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los numerales fraccionarios correspondientes a ciento, mil, millón, billón, etc. se construyen con el sufijo -èsim..
        /// </summary>
        internal static string FraccionNota2 {
            get {
                return ResourceManager.GetString("FraccionNota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracción.
        /// </summary>
        internal static string FraccionTipo {
            get {
                return ResourceManager.GetString("FraccionTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        internal static string NotasTitulo {
            get {
                return ResourceManager.GetString("NotasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias.
        /// </summary>
        internal static string ReferenciasTitulo {
            get {
                return ResourceManager.GetString("ReferenciasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo se escribe ... en letras en español?.
        /// </summary>
        internal static string ValorNumericoTitulo {
            get {
                return ResourceManager.GetString("ValorNumericoTitulo", resourceCulture);
            }
        }
    }
}
