//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjetivo.
        /// </summary>
        internal static string AdjetivoOpcion {
            get {
                return ResourceManager.GetString("AdjetivoOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjetivo y pronombre femenino.
        /// </summary>
        internal static string AdjetivoPronombreFOpcion {
            get {
                return ResourceManager.GetString("AdjetivoPronombreFOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de agua es de … litros..
        /// </summary>
        internal static string CardinalEjemplo1 {
            get {
                return ResourceManager.GetString("CardinalEjemplo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La distancia entre ambas ciudades es de … kilómetros..
        /// </summary>
        internal static string CardinalEjemplo2 {
            get {
                return ResourceManager.GetString("CardinalEjemplo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso total del paquete es de ... kilogramos..
        /// </summary>
        internal static string CardinalEjemplo3 {
            get {
                return ResourceManager.GetString("CardinalEjemplo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La temperatura actual en la ciudad es de ... grados..
        /// </summary>
        internal static string CardinalEjemplo4 {
            get {
                return ResourceManager.GetString("CardinalEjemplo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El temps estimat d&apos;arribada és de ... minuts..
        /// </summary>
        internal static string CardinalEjemplo5 {
            get {
                return ResourceManager.GetString("CardinalEjemplo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los numerales cardinales expresan la numeración natural..
        /// </summary>
        internal static string CardinalNota1 {
            get {
                return ResourceManager.GetString("CardinalNota1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las formas del 17 al 19 están compuestas por el alomorfo di-, o de-, como simplificación de manantial. Las decenas a partir del 30 presentan la terminación -nta..
        /// </summary>
        internal static string CardinalNota2 {
            get {
                return ResourceManager.GetString("CardinalNota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Las decenas a partir del 30 presentan la terminación -nta..
        /// </summary>
        internal static string CardinalNota3 {
            get {
                return ResourceManager.GetString("CardinalNota3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Del 21 al 29 van coordinados con la conjunción y: veintiuno, ..., veintinueve..
        /// </summary>
        internal static string CardinalNota4 {
            get {
                return ResourceManager.GetString("CardinalNota4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Del 31 al 99, y las centésimas (200 al 900), son yuxtapuestos con un guion: treinta y uno, ..., noventa y nueve, ..., doscientos, ..., novecientos..
        /// </summary>
        internal static string CardinalNota5 {
            get {
                return ResourceManager.GetString("CardinalNota5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En los otros casos no hay guion: ciento dos (102), dos mil (2.000), ciento veintidós (122), dos mil doscientos veintidós (2.222)..
        /// </summary>
        internal static string CardinalNota6 {
            get {
                return ResourceManager.GetString("CardinalNota6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viquipèdia l&apos;Enciclopèdia Lliure. Numerals en català. Cardinals. https://ca.wikipedia.org/wiki/Numerals_en_catal%C3%A0.
        /// </summary>
        internal static string CardinalReferencia1 {
            get {
                return ResourceManager.GetString("CardinalReferencia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consorci per a la Normalització Lingüística. 6 ELS NUMERALS. NUMERALS CARDINALS. https://www.cpnl.cat/gramatica/24/6-els-numerals.
        /// </summary>
        internal static string CardinalReferencia2 {
            get {
                return ResourceManager.GetString("CardinalReferencia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Omniglot. Numbers in Catalan. https://www.omniglot.com/language/numbers/catalan.htm?utm_source=chatgpt.com.
        /// </summary>
        internal static string CardinalReferencia3 {
            get {
                return ResourceManager.GetString("CardinalReferencia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerard Vilanova. Web de llengua catalana de Gerard Vilanova. Els determinants numerals, quantitatius i indefinits. https://gerardvilanova.jimdofree.com/nivell-1/unitat-6/gram%C3%A0tica/.
        /// </summary>
        internal static string CardinalReferencia4 {
            get {
                return ResourceManager.GetString("CardinalReferencia4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cardinal.
        /// </summary>
        internal static string CardinalTipo {
            get {
                return ResourceManager.GetString("CardinalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalan.
        /// </summary>
        internal static string CatalanTipo {
            get {
                return ResourceManager.GetString("CatalanTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a centavo.
        /// </summary>
        internal static string Centavo {
            get {
                return ResourceManager.GetString("Centavo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a centavos.
        /// </summary>
        internal static string Centavos {
            get {
                return ResourceManager.GetString("Centavos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a céntimo.
        /// </summary>
        internal static string Centimo {
            get {
                return ResourceManager.GetString("Centimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a céntimos.
        /// </summary>
        internal static string Centimos {
            get {
                return ResourceManager.GetString("Centimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso del paquete es de … kilogramos..
        /// </summary>
        internal static string DecimalEjemplo1 {
            get {
                return ResourceManager.GetString("DecimalEjemplo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El velocímetro marcaba … kilómetros por hora..
        /// </summary>
        internal static string DecimalEjemplo2 {
            get {
                return ResourceManager.GetString("DecimalEjemplo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El termòmetre marcava … graus Celsius..
        /// </summary>
        internal static string DecimalEjemplo3 {
            get {
                return ResourceManager.GetString("DecimalEjemplo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La distància total era de ... quilòmetres..
        /// </summary>
        internal static string DecimalEjemplo4 {
            get {
                return ResourceManager.GetString("DecimalEjemplo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los números decimales se escriben siempre con cifras..
        /// </summary>
        internal static string DecimalNota1 {
            get {
                return ResourceManager.GetString("DecimalNota1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en catalán las fracciones decimales se indican siempre con una coma.
        /// </summary>
        internal static string DecimalNota2 {
            get {
                return ResourceManager.GetString("DecimalNota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cinquè. NUMERACIÓ. ELS NOMBRES DECIMALS!!!. https://sites.google.com/vedruna.cat/vedrunatona5/matem%C3%A0tiques/sistema-de-numeraci%C3%B3-decimal.
        /// </summary>
        internal static string DecimalReferencia1 {
            get {
                return ResourceManager.GetString("DecimalReferencia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Universitat Pompeu Fabra Barcelona. Números decimals. https://www.upf.edu/web/llibre-estil/numeros-decimals.
        /// </summary>
        internal static string DecimalReferencia2 {
            get {
                return ResourceManager.GetString("DecimalReferencia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal.
        /// </summary>
        internal static string DecimalTipo {
            get {
                return ResourceManager.GetString("DecimalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dolar.
        /// </summary>
        internal static string Dolar {
            get {
                return ResourceManager.GetString("Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dolares.
        /// </summary>
        internal static string Dolares {
            get {
                return ResourceManager.GetString("Dolares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dolar.
        /// </summary>
        internal static string DolarTipo {
            get {
                return ResourceManager.GetString("DolarTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplos.
        /// </summary>
        internal static string EjemplosTitulo {
            get {
                return ResourceManager.GetString("EjemplosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a euro.
        /// </summary>
        internal static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a euros.
        /// </summary>
        internal static string Euros {
            get {
                return ResourceManager.GetString("Euros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Euros.
        /// </summary>
        internal static string EurosTipo {
            get {
                return ResourceManager.GetString("EurosTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión con adjetivo.
        /// </summary>
        internal static string ExpresionAdjetivoOpcion {
            get {
                return ResourceManager.GetString("ExpresionAdjetivoOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresion.
        /// </summary>
        internal static string ExpresionTitulo {
            get {
                return ResourceManager.GetString("ExpresionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma femenina.
        /// </summary>
        internal static string FormFemOpcion {
            get {
                return ResourceManager.GetString("FormFemOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma masculina.
        /// </summary>
        internal static string FormMasOpcion {
            get {
                return ResourceManager.GetString("FormMasOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiero ... de chocolate. .
        /// </summary>
        internal static string FraccionarioEjemplo1 {
            get {
                return ResourceManager.GetString("FraccionarioEjemplo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sequía afecta a ... de la región. .
        /// </summary>
        internal static string FraccionarioEjemplo2 {
            get {
                return ResourceManager.GetString("FraccionarioEjemplo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Només hem utilitzat ... dels recursos disponibles..
        /// </summary>
        internal static string FraccionarioEjemplo3 {
            get {
                return ResourceManager.GetString("FraccionarioEjemplo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaig llegir ... del llibre abans de dormir..
        /// </summary>
        internal static string FraccionarioEjemplo4 {
            get {
                return ResourceManager.GetString("FraccionarioEjemplo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fraccionario.
        /// </summary>
        internal static string FraccionarioTipo {
            get {
                return ResourceManager.GetString("FraccionarioTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las formas de los numerales fraccionarios coinciden con las del numerales ordinales con algunas excepciones: medio(2), cuarto(4), tercio(3) o décimo(10).
        /// </summary>
        internal static string FraccionNota1 {
            get {
                return ResourceManager.GetString("FraccionNota1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los numerales fraccionarios correspondientes a ciento, mil, millón, billón, etc. se construyen con el sufijo -èsim..
        /// </summary>
        internal static string FraccionNota2 {
            get {
                return ResourceManager.GetString("FraccionNota2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antoni Llàcer. Com llegim les fraccions? Escola d&apos;Adults de Canovelles, 2021. https://agora.xtec.cat/cfacanovelles/matematiques-i/com-llegim-les-fraccions/.
        /// </summary>
        internal static string FraccionReferencia1 {
            get {
                return ResourceManager.GetString("FraccionReferencia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institut d&apos;Estudis Catalans, Els numerals fraccionaris. Gramàtica essencial de la llengua catalana. https://geiec.iec.cat/text/12.3.2.
        /// </summary>
        internal static string FraccionReferencia2 {
            get {
                return ResourceManager.GetString("FraccionReferencia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consorci per a la Normalització Lingüística. 6 ELS NUMERALS. ELS PARTITIUS. https://www.cpnl.cat/gramatica/24/6-els-numerals.
        /// </summary>
        internal static string FraccionReferencia3 {
            get {
                return ResourceManager.GetString("FraccionReferencia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracción.
        /// </summary>
        internal static string FraccionTipo {
            get {
                return ResourceManager.GetString("FraccionTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplicativo.
        /// </summary>
        internal static string MultiplicativoTipo {
            get {
                return ResourceManager.GetString("MultiplicativoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi cuenta bancaria quedó en … euros después de pagar las facturas..
        /// </summary>
        internal static string NegativoEjemplo1 {
            get {
                return ResourceManager.GetString("NegativoEjemplo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La diferencia de potencial eléctrico fue de … voltios..
        /// </summary>
        internal static string NegativoEjemplo2 {
            get {
                return ResourceManager.GetString("NegativoEjemplo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negativo.
        /// </summary>
        internal static string NegativoTipo {
            get {
                return ResourceManager.GetString("NegativoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro oral, no apropiado para escribir.
        /// </summary>
        internal static string NoApropiadoOpcion {
            get {
                return ResourceManager.GetString("NoApropiadoOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        internal static string NotasTitulo {
            get {
                return ResourceManager.GetString("NotasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número formateado.
        /// </summary>
        internal static string NumeroFormateadoTitulo {
            get {
                return ResourceManager.GetString("NumeroFormateadoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordinal.
        /// </summary>
        internal static string OrdinalTipo {
            get {
                return ResourceManager.GetString("OrdinalTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pesos.
        /// </summary>
        internal static string Pesos {
            get {
                return ResourceManager.GetString("Pesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string PesoTipo {
            get {
                return ResourceManager.GetString("PesoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poligono.
        /// </summary>
        internal static string PoligonoTipo {
            get {
                return ResourceManager.GetString("PoligonoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias.
        /// </summary>
        internal static string ReferenciasTitulo {
            get {
                return ResourceManager.GetString("ReferenciasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sintagma nominal.
        /// </summary>
        internal static string SintagmaNominalOpcion {
            get {
                return ResourceManager.GetString("SintagmaNominalOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo, adjetivo y pronombre.
        /// </summary>
        internal static string SusAdProTitulo {
            get {
                return ResourceManager.GetString("SusAdProTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo femenino.
        /// </summary>
        internal static string SustantivoFOpcion {
            get {
                return ResourceManager.GetString("SustantivoFOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo masculino.
        /// </summary>
        internal static string SustantivoMOpcion {
            get {
                return ResourceManager.GetString("SustantivoMOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sustantivo.
        /// </summary>
        internal static string SustantivoOpcion {
            get {
                return ResourceManager.GetString("SustantivoOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las opciones y funciones.
        /// </summary>
        internal static string TituloOpciones {
            get {
                return ResourceManager.GetString("TituloOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valenciano: .
        /// </summary>
        internal static string ValencianoTipo {
            get {
                return ResourceManager.GetString("ValencianoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor numérico.
        /// </summary>
        internal static string ValorNumericoTitulo {
            get {
                return ResourceManager.GetString("ValorNumericoTitulo", resourceCulture);
            }
        }
    }
}
